### ISSUE TITLE
[Request] Keep and use a local copy of used repositories

### ISSUE THREAD

**Issue by realtebo** [BurgerZ/jBART#186]
We work on >40 ROMS, but we use < 10 repositories. 
Why the tool must download them every time instead of keep a local copy and reuse as needed?

We'd like a way to configure cli.recompile.conf to use a local copy of repositories.

**Comment by KcNirvana** [comment]
Hi...
Why don't you use a local file or directory instead of a repo?

Repositories possible config combinations:

Linux:
folder::/home/username/MIUI-v5-Translation=Name to show in repos list
package::/home/username/MIUI-v2-Translation.zip=Name to show in repos list

Windows:
folder::C:\\Users\\username\\Desktop\\MIUI-v5-Translation=Name to show in repos list
package::C:\\Users\\username\\Desktop\\MIUI-v2-Translation.zip=Name to show in repos list

**Comment by ale8530** [comment]
Closed this issue thanks your suggest work perfectly!


Thanks
